version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: nuget restore ./TeamToolsExtended/TeamToolsExtended.sln
build:
  project: ./TeamToolsExtended/TeamToolsExtended.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - vlado547@outlook.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: 1B0sVIZsV087WAibarFpJ7S3T1JjOO1x6
