version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: nuget restore ./TeamToolsExtended/TeamToolsExtended.sln
build:
  project: ./TeamToolsExtended/TeamToolsExtended.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - vlado547@outlook.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: XgFQ6i+g21o6ZkJzOW6lgqXSromINzR4OTFTE5245GlFuSDLRBMQ9qag2mGeiih9

after_test: 
        - TeamToolsExtended\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"TeamToolsExtended\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single TeamToolsExtended\TeamTools.Logic.Tests\bin\Debug\TeamTools.Logic.Tests.dll" -output:cover.xml

        - MeetMe\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml
